fixtures:
  repositories:
    stdlib:
      repo:   "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    augeasproviders_core:
      repo:   "https://github.com/hercules-team/augeasproviders_core.git"
    augeasproviders_sysctl:
      repo:   "https://github.com/hercules-team/augeasproviders_sysctl.git"
    docker:
      repo:   "https://github.com/puppetlabs/puppetlabs-docker.git"
    systemd:
      repo:   "https://github.com/camptocamp/puppet-systemd.git"
    yumrepo_core:
      repo: "https://github.com/puppetlabs/puppetlabs-yumrepo_core.git"
      puppet_version: ">= 6.0.0"
  symlinks:
   "thehive": "#{source_dir}"
